### ISSUE TITLE
load-gulp-config not finding the directory with the js files?

### ISSUE THREAD

**Issue by ebhemmanuel** [adriancmiranda/load-gulp-config#1]
So I've setup my js inside the gulp directory ( as is default ). I'm testing the sass build run under the yaml file. Yet it says it doesn't recognize the build command under the gulpfile. Isn't the load-gulp-config suppose to look into the directory like load-grunt-config? I'm sure I'm doing something wrong since I'm new to gulp in general. 

Yaml File:

```
build:
- 'sass:dev'
- 'sass:dist'
```

The sass.js file inside of the gulp dir:

```
module.exports = function(gulp, data, util, taskName){
    'use strict';
        gulp.task('dev', function () {
            gulp.src('<%= _config.source.paths.css %>')
                .pipe(sass({
                    outputStyle: 'expanded',
                    quiet: true
                }))
                .pipe(cssnano())
                .pipe(gulp.dest('<%= _config.tmp.paths.css %>'))
        })
        gulp.task('dist', function () {
            gulp.src('<%= _config.source.paths.css %>')
                .pipe(sass({
                    outputStyle: 'compressed',
                    quiet: true
                }))
                .pipe(cssnano())
                .pipe(gulp.dest('<%= _config.output.paths.css %>'))
        })
};
```

**Comment by adriancmiranda** [comment]
@ebhemmanuel You're right! I don't know what means _config from `e.g. '<%= _config.source.paths.css %>'` but, yes!  This should look into the directory like [load-grunt-config](https://npmjs.com/package/load-grunt-config)

> **P.S.**: I putted a scaffold for you in `example` directory. If you'll have any problem yet, let me know 😉

**Comment by ebhemmanuel** [comment]
@adriancmiranda So as far as I can tell from the existing files, the _config is referencing the _config.js file inside of the grunt/gulpfolder. So it's trying to reference itself as a root level?

**Comment by adriancmiranda** [comment]
@ebhemmanuel My idea of the paths (mainly to make smooth the change of the structure) uses [this](https://github.com/adriancmiranda/load-gulp-config/blob/master/example/package.json#L18-L30) object [here](https://github.com/adriancmiranda/load-gulp-config/blob/master/example/gulpfile.js#L39) and creates a method to each entry like [this](https://github.com/adriancmiranda/load-gulp-config/blob/master/example/tasks/styles.js#L40) with the dirname from [this](https://github.com/adriancmiranda/load-gulp-config/blob/master/example/package.json#L19) as `util.dir.styles('**/*.{scss,sass}')` generating something like `'Source/styles/**/*.{scss,sass}'`. All relative to the root of your project. I don't change any other behavior from the gulp or any path after that, so if `e.g. <%= _config.source.paths.css %>` works out of load-gulp-config, should work in load-gulp-config too (if don't work, I can see it for you). 
For now, I'll close this issue. Feel free to reopen it if you need 😉
